# Association Rules

## Example 1: Generating Association Rules from Frequent Itemsets

To demonstrate the usage of the `generate_rules` method, we first create a pandas `DataFrame` of frequent itemsets as generated by the `fpgrowth` function:

In [ ]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

dataset = [['Nissan Skyline', 'Toyota Supra', 'Mazda RX-7', 'Honda NSX', 'Subaru Impreza', 'Mitsubishi Lancer'],
  ['Toyota Supra', 'Mazda RX-7', 'Honda S2000', 'Subaru Impreza', 'Mitsubishi Lancer'],
  ['Nissan Skyline', 'Honda Civic', 'Subaru Impreza', 'Mitsubishi Lancer'],
  ['Nissan Skyline', 'Toyota AE86', 'Mazda MX-5', 'Subaru Impreza', 'Honda NSX'],
  ['Mazda MX-5', 'Toyota Supra', 'Toyota Supra', 'Subaru Impreza', 'Nissan Silvia', 'Honda S2000']]

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = fpgrowth(df, min_support=0.6, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

   support                             itemsets
0      1.0                     (Subaru Impreza)
1      0.6                       (Toyota Supra)
2      0.6                     (Nissan Skyline)
3      0.6                  (Mitsubishi Lancer)
4      0.6       (Subaru Impreza, Toyota Supra)
5      0.6     (Subaru Impreza, Nissan Skyline)
6      0.6  (Subaru Impreza, Mitsubishi Lancer)